FROM python:3.12-slim

# Install Dagster host process dependencies
RUN pip install --no-cache-dir \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-docker

# Define Dagster home inside the container
ENV DAGSTER_HOME=/opt/dagster/dagster_home

RUN mkdir -p $DAGSTER_HOME

# Copy Dagster configuration into the image
# WORKDIR /opt/dagster
# COPY dagster.yaml workspace_docker.yaml workspace.yaml ./

# Copy Dagster configuration into the image
# WORKDIR $DAGSTER_HOME
# COPY dagster.yaml $DAGSTER_HOME/
# COPY dagster.yaml workspace.yaml workspace_docker.yaml $DAGSTER_HOME/ 